---
apiVersion: v1
kind: Namespace
metadata:
   name: trident
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trident-installer
  namespace: trident
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trident-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: trident-installer
  namespace: trident
---
apiVersion: batch/v1
kind: Job
metadata:
  name: trident-installer
  namespace: trident
spec:
  template:
    spec:
      serviceAccountName: trident-installer
      containers:
        - name: trident-installer
          image: fabianborn/dev-trident-installer:20.10.0
          volumeMounts:
            - name: manifests
              mountPath: /manifests
            - name: backend
              mountPath: /backend
          command: ["/bin/sh"]
          args: ["/manifests/install.sh"]
      restartPolicy: OnFailure
      volumes:
        - name: manifests
          configMap:
            name: trident-installer
        - name: backend
          secret:
            secretName: trident-installer-backend
---
apiVersion: v1
kind: Secret
metadata:
  name: trident-installer-backend
  namespace: trident
stringData:
  backend.json: |-
    {
      "version": 1,
      "storageDriverName": "ontap-nas",
      "backendName": "ontapnas",
      "managementLIF": "192.168.69.60",
      "dataLIF": "192.168.69.61",
      "svm": "optimusprime",
      "username": "vsadmin",
      "password": "netapp123",
      "storagePrefix": "nas"
    }
  backend-san.json: |-
    {
      "version": 1,
      "storageDriverName": "ontap-san",
      "backendName": "ontapsan",
      "managementLIF": "192.168.69.63",
      "svm": "bumblebee",
      "username": "vsadmin",
      "password": "netapp123",
      "storagePrefix": "prod_k8s",
      "igroupName": "prod_k8s",
      "useCHAP": false,
      "defaults": {
          "spaceReserve": "volume",
          "spaceAllocation": "false",
          "snapshotPolicy": "none",
          "snapshotReserve": "0"
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trident-installer
  namespace: trident
data:
  storage_class_trident.yaml: |-
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: trident
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-nas"
    allowVolumeExpansion: True
    ---
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: trident-
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
    provisioner: netapp.io/trident
    parameters:
      backendType: "ontap-nas"
    allowVolumeExpansion: True
  install.sh: |-
    set -ex
    sleep 3 
    kubectl apply -f /opt/trident-installer/deploy/crds/trident.netapp.io_tridentprovisioners_crd_post1.16.yaml
    kubectl apply -f /opt/trident-installer/deploy/bundle.yaml
    kubectl apply -f /opt/trident-installer/deploy/crds/tridentprovisioner_cr.yaml
    kubectl apply -f https://raw.githubusercontent.com/fabian-born/k8s-trident-installer/master/patch/tprov-rke-patch.yaml
    sleep 10
    i="0"
    until kubectl describe tprov trident -n trident | grep "Status:.*Installed"
    do
      sleep 30
      if [ ! $i -lt 30 ]; then
        exit 1
      fi
    done
    /opt/trident-installer/tridentctl -n trident create backend -f /backend/backend.json
    kubectl apply -f /manifests/storage_class_trident.yaml
    kubectl delete job.batch -n trident trident-installer
